### ISSUE TITLE
WHAM version conflicts with DPVO

### ISSUE THREAD

**Issue by hanlinniu** [yohanshin/WHAM#100]
When I run WHAM, it reminds me I haven't installed DPVO properly, then I try to install DPVO following the tutorial: [https://github.com/princeton-vl/DPVO/tree/58338357611e7cf3563ed90f82168da7f8741d24](url)  But, I found after I installed DPVO, the conda environment of WHAM changed, and I cannot run WHAM anymore, any suggestion?  I also found DPVO is using python 3.10, and WHAM is using python 3.9, is there any conflict here?

**Comment by hanlinniu** [comment]
Currently, I have this error: 

2024-06-15 21:10:17.769 | INFO     | __main__:<module>:209 - GPU name -> NVIDIA GeForce RTX 3080 Ti Laptop GPU
2024-06-15 21:10:17.769 | INFO     | __main__:<module>:210 - GPU feat -> _CudaDeviceProperties(name='NVIDIA GeForce RTX 3080 Ti Laptop GPU', major=8, minor=6, total_memory=16125MB, multi_processor_count=58)
2024-06-15 21:10:18.809 | INFO     | lib.models:build_network:36 - => loaded checkpoint 'checkpoints/wham_vit_bedlam_w_3dpw.pth.tar' 
load checkpoint from local path: /home/hanlin/WHAM/checkpoints/vitpose-h-multi-coco.pth
Load backbone weight: /home/hanlin/WHAM/checkpoints/hmr2a.ckpt
Traceback (most recent call last):
  File "/home/hanlin/WHAM/demo.py", line 224, in <module>
    run(cfg,
  File "/home/hanlin/WHAM/demo.py", line 65, in run
    detector.track(img, fps, length)
  File "/home/hanlin/WHAM/lib/models/preproc/detector.py", line 82, in track
    bboxes = self.bbox_model.predict(
  File "/home/hanlin/anaconda3/envs/wham/lib/python3.9/site-packages/ultralytics/engine/model.py", line 446, in predict
    self.predictor.setup_model(model=self.model, verbose=is_cli)
  File "/home/hanlin/anaconda3/envs/wham/lib/python3.9/site-packages/ultralytics/engine/predictor.py", line 303, in setup_model
    self.model = AutoBackend(
  File "/home/hanlin/anaconda3/envs/wham/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/hanlin/anaconda3/envs/wham/lib/python3.9/site-packages/ultralytics/nn/autobackend.py", line 144, in __init__
    model = model.fuse(verbose=verbose)
  File "/home/hanlin/anaconda3/envs/wham/lib/python3.9/site-packages/ultralytics/nn/tasks.py", line 184, in fuse
    m.conv = fuse_conv_and_bn(m.conv, m.bn)  # update conv
  File "/home/hanlin/anaconda3/envs/wham/lib/python3.9/site-packages/ultralytics/utils/torch_utils.py", line 205, in fuse_conv_and_bn
    fusedconv.weight.copy_(torch.mm(w_bn, w_conv).view(fusedconv.weight.shape))
RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`


I am using cuda 11.3, cudnn 8.2

**Comment by ChrisChenYh** [comment]
runing `unset LD_LIBRARY_PATH` may be helpful

**Comment by ChrisChenYh** [comment]
And how you solve the version conflicts? First install DPVO, and then modify the environments of WHAM?

**Comment by SoCool668** [comment]
How to solve the following code in the process of installation, thank you
Processing /content/WHAM/third-party/DPVO
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
/content/WHAM
