### ISSUE TITLE
Error when running in docker

### ISSUE THREAD

**Issue by zshyang** [yohanshin/WHAM#103]
I got the following error when trying to use the docker image.
``` bash
Status: Downloaded newer image for yusun9/wham-vitpose-dpvo-cuda11.3-python3.9:latest
/opt/conda/lib/python3.9/site-packages/mmcv/cnn/bricks/transformer.py:27: UserWarning: Fail to import ``MultiScaleDeformableAttention`` from ``mmcv.ops.multi_scale_deform_attn``, You should install ``mmcv-full`` if you need this module. 
  warnings.warn('Fail to import ``MultiScaleDeformableAttention`` from '
2024-06-24 22:29:51.325 | INFO     | __main__:<module>:209 - GPU name -> Quadro RTX 5000
2024-06-24 22:29:51.326 | INFO     | __main__:<module>:210 - GPU feat -> _CudaDeviceProperties(name='Quadro RTX 5000', major=7, minor=5, total_memory=16117MB, multi_processor_count=48)
2024-06-24 22:29:52.174 | INFO     | lib.models:build_network:36 - => loaded checkpoint 'checkpoints/wham_vit_bedlam_w_3dpw.pth.tar' 
apex is not installed
apex is not installed
apex is not installed
Use load_from_local loader
Load backbone weight: /code/checkpoints/hmr2a.ckpt
Traceback (most recent call last):
  File "/code/demo.py", line 223, in <module>
    run(cfg, 
  File "/code/demo.py", line 69, in run
    slam.track()
  File "/code/lib/models/preproc/slam.py", line 62, in track
    self.slam(t, image, intrinsics)
  File "/opt/conda/lib/python3.9/site-packages/dpvo/dpvo.py", line 331, in __call__
    self.network.patchify(image,
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/dpvo/net.py", line 136, in forward
    imap = altcorr.patchify(imap[0], coords, 0).view(b, -1, DIM, 1, 1)
  File "/opt/conda/lib/python3.9/site-packages/dpvo/altcorr/correlation.py", line 57, in patchify
    offset = (coords - coords.floor()).to(net.device)
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

**Comment by TongZhangTHU** [comment]
@zshyang I met the same question. Have you solve it now?

**Comment by adk-tl** [comment]
same here; followed the docker setup verbatim, reverted to e2b72fc0 (date of documentation update), same problem. I am using a Tesla T4, which should be fully supported by Cuda 11.3 and pytorch 1.11.0. @zshyang @TongZhangTHU were you able to resolve this issue?
