### ISSUE TITLE
'CustomDataset' object has no attribute 'prefix'

### ISSUE THREAD

**Issue by tedlin0913** [yohanshin/WHAM#126]
Hello, I was trying out using docker environment you provided in docs/API.md, and I encountered the following error: 
```bash
File "/code/lib/data/datasets/dataset_custom.py", line 76, in __getitem__
    kp2d = torch.from_numpy(self.tracking_results[index][self.prefix + 'keypoints']).float()
AttributeError: 'CustomDataset' object has no attribute 'prefix'
```
```bash
>>> wham_model = WHAM_API()
2024-11-21 07:11:05.588 | INFO     | lib.models:build_network:36 - => loaded checkpoint 'checkpoints/wham_vit_bedlam_w_3dpw.pth.tar' 
Use load_from_local loader
Load backbone weight: /code/checkpoints/hmr2a.ckpt
>>> input_video_path = 'examples/IMG_9732.mov'
>>> results, tracking_results, slam_results = wham_model(input_video_path)
Feature extraction ... |################################| 660/660Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/code/wham_api.py", line 133, in __call__
    results = self.wham_inference(tracking_results, slam_results, width, height, fps, output_dir)
  File "/opt/conda/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/code/wham_api.py", line 99, in wham_inference
    for batch in dataset:
  File "/code/lib/data/datasets/dataset_custom.py", line 76, in __getitem__
    kp2d = torch.from_numpy(self.tracking_results[index][self.prefix + 'keypoints']).float()
AttributeError: 'CustomDataset' object has no attribute 'prefix'
```

**Comment by Amir-Mann** [comment]
I also ran into the same problem (with different setup and command, but same error at the same point in the code)

**Comment by Amir-Mann** [comment]
The issue in my case was parially failing to run the fetch_demo_data.sh script, to which I gave wrong SMPL credentials.

**Comment by Amir-Mann** [comment]
Fixed by adding:
```
     def __init__(self, cfg, tracking_results, slam_results, width, height, fps):
        self.prefix = ''
```
