### ISSUE TITLE
eval EMDB

### ISSUE THREAD

**Issue by xiaoyudanaa** [yohanshin/WHAM#17]
![image](https://github.com/yohanshin/WHAM/assets/77732714/79908010-8d2b-48de-9a4e-26e50d6c434a)
Exciting work. I have a problem with the error in the picture when I evaluate on EMDB(1). Do you know how to solve it? (Both 3DPW and RICH are runnable)

**Comment by yohanshin** [comment]
Hi @xiaoyudanaa , as mentioned at this [line](https://github.com/yohanshin/WHAM/blob/a4fd7b064cdc23d69f4ea4ba377ee419b3d23f33/lib/eval/evaluate_emdb.py#L32) in the evaluation script, the current code requires EMDB to be downloaded and stored at `./dataset/`. Please visit the official [website](https://eth-ait.github.io/emdb/) to register and download the EMDB dataset to run the current evaluation. Sorry for the confusion!

**Comment by zehongs** [comment]
Hi @yohanshin , would you be willing to upload the implementation of RTE, ROE, and ERVE for testing the EMDB-2?

**Comment by JoeLeelyf** [comment]
Hi @yohanshin @xiaoyudanaa, how did you successfully evaluate WHAM on RICH? I try hard to make sure that I have strictly followed the setup instructions provided in the README file, and indeed successfully evaluate WHAM on 3DPW But when it comes to RICH, I encountered two main problems as follows:
1. 
![image](https://github.com/yohanshin/WHAM/assets/107903202/0d52c45c-757d-44c6-bb73-0be62e0f63fb)
2. 
![image](https://github.com/yohanshin/WHAM/assets/107903202/184f5eef-d0f5-44c6-b95c-84ea8cfdabe7)
The first one can be partly tackled by setting `cfg.FLIP_EVAL = False`, but I want to know what this parameter means exactly. The second may be due to the miss of smplx models, and I have noticed that you haven't mentioned this in your README file :)

**Comment by GaigeY** [comment]
> Hi @yohanshin @xiaoyudanaa, how did you successfully evaluate WHAM on RICH? I try hard to make sure that I have strictly followed the setup instructions provided in the README file, and indeed successfully evaluate WHAM on 3DPW But when it comes to RICH, I encountered two main problems as follows: 1. ![image](https://private-user-images.githubusercontent.com/107903202/313483007-0d52c45c-757d-44c6-bb73-0be62e0f63fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwNTk5NTIsIm5iZiI6MTcxNDA1OTY1MiwicGF0aCI6Ii8xMDc5MDMyMDIvMzEzNDgzMDA3LTBkNTJjNDVjLTc1N2QtNDRjNi1iYjczLTBiZTYyZTBmNjNmYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNVQxNTQwNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZDFjMTg1Y2Q3OWQ5YzAyZjg1ODRlYjNhNTM3ZTkzNjU1MzkzZDQwZjY5ZWNiM2Q2OTY5YTU1NmQ5MTc1ZGQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.czeIwcZPy2_4r59j0WyaRRpHpt-O2MsF-dZ-8zzGLiA) 2. ![image](https://private-user-images.githubusercontent.com/107903202/313483058-184f5eef-d0f5-44c6-b95c-84ea8cfdabe7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwNTk5NTIsIm5iZiI6MTcxNDA1OTY1MiwicGF0aCI6Ii8xMDc5MDMyMDIvMzEzNDgzMDU4LTE4NGY1ZWVmLWQwZjUtNDRjNi1iOTVjLTg0ZWE4Y2ZkYWJlNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNVQxNTQwNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZTk0MTJkZWJkNmY1ZWEzYzgwZWUwN2YyMjkxOTJlYzZmOWQwNTRlZmRhZmQwYzBlMGU1ZGY1ZjY3NjI1NzA3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NCYjqhvW34bettOytrrO5fsSQCHoxwc65iGKEsf30Qo) The first one can be partly tackled by setting `cfg.FLIP_EVAL = False`, but I want to know what this parameter means exactly. The second may be due to the miss of smplx models, and I have noticed that you haven't mentioned this in your README file :)

Hi, thanks for you experience sharing. To the second problem, you should download the THREE `SMPLX_GENDER.npz` files from [the link](https://download.is.tue.mpg.de/download.php?domain=smplx&sfile=models_smplx_v1_1.zip) provided by smplx, and put them into `dataset/body_models/smplx/` folder.

**Comment by OliverSTH** [comment]
> ![image](https://private-user-images.githubusercontent.com/77732714/293620813-79908010-8d2b-48de-9a4e-26e50d6c434a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2OTQxMTksIm5iZiI6MTcyNTY5MzgxOSwicGF0aCI6Ii83NzczMjcxNC8yOTM2MjA4MTMtNzk5MDgwMTAtOGQyYi00OGRlLTlhNGUtMjZlNTBkNmM0MzRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA3VDA3MjMzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzNmY4NTdkNzczOGU0N2ZiY2M3NTExMjExYTU5MTNhNWIwZGIwNzMzZTNmODA2ZWI3ZTc0MWM0MDgyOWQxYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F2SFCyKwbPx1k2CsqC7xr0ms3KqIHb8PkoUoR5ElIDE) Exciting work. I have a problem with the error in the picture when I evaluate on EMDB(1). Do you know how to solve it? (Both 3DPW and RICH are runnable)

Hi, @xiaoyudanaa 
I would like to ask you why I can't evaluate Rich dataset when I run this command.
```
python -m lib.eval.evaluate_rich --cfg configs/yamls/demo.yaml TRAIN.CHECKPOINT checkpoints/wham_vit_w_3dpw.pth.tar
```

Do you do the same thing?
I have the following problem. Do you know how to solve it?
```
Traceback (most recent call last):
  File "/home/dvlab/anaconda3/envs/wham/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/dvlab/anaconda3/envs/wham/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/dvlab/WHAM/lib/eval/evaluate_rich.py", line 156, in <module>
    main(cfg, args)
  File "/home/dvlab/anaconda3/envs/wham/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/dvlab/WHAM/lib/eval/evaluate_rich.py", line 67, in main
    flipped_batch = eval_loader.dataset.load_data(i, True)
  File "/home/dvlab/WHAM/lib/data/datasets/dataset_eval.py", line 31, in load_data
    target = self.__getitem__(index)
  File "/home/dvlab/WHAM/lib/data/datasets/dataset_eval.py", line 39, in __getitem__
    target = self.get_data(index)
  File "/home/dvlab/WHAM/lib/data/datasets/dataset_eval.py", line 110, in get_data
    target = self.prepare_inputs(index, target)
  File "/home/dvlab/WHAM/lib/data/datasets/dataset_eval.py", line 76, in prepare_inputs
    data = self.labels[self.prefix + key][index][1:]
IndexError: list index out of range

```
Thank you for your reply.
