### ISSUE TITLE
ValueError: need at least one array to concatenate

### ISSUE THREAD

**Issue by DarrenKey** [yohanshin/WHAM#31]
Thank you for the code and repo! When running on some custom videos, I get the following errors, but the example file works as expected:

```
Traceback (most recent call last):
  File "/home/WHAM/demo.py", line 145, in <module>
    run(cfg, args.video, output_pth, network, args.calib, visualize=args.visualize)
  File "/home/WHAM/demo.py", line 107, in run
    run_vis_on_demo(cfg, video, results, output_pth, network.smpl, vis_global=True)
  File "/home/WHAM/lib/vis/run_vis.py", line 43, in run_vis_on_demo
    renderer.set_ground(scale, cx.item(), cz.item())
  File "/home/WHAM/lib/vis/renderer.py", line 171, in set_ground
    v, f, vc, fc = map(torch.from_numpy, checkerboard_geometry(length=length, c1=center_x, c2=center_z, up="y"))
  File "/home/WHAM/lib/vis/tools.py", line 207, in checkerboard_geometry
    vertices = np.concatenate(vertices, axis=0).astype(np.float32)
  File "<__array_function__ internals>", line 180, in concatenate
ValueError: need at least one array to concatenate```

**Comment by WenjiaWang0312** [comment]
https://github.com/yohanshin/WHAM/issues/29
see this please

**Comment by DarrenKey** [comment]
Thanks, closing!
