### ISSUE TITLE
After commit with --run_smplify getting issue "No such file or directory: 'configs/yamls/demo_w_fit.yaml'"

### ISSUE THREAD

**Issue by mrEuler** [yohanshin/WHAM#57]
```
(wham) ubuntu@ip-172-31-38-235:~/WHAM$ python demo.py --video examples/tennis1.mp4 --visualize --run_smplify
apex is not installed
apex is not installed
apex is not installed
/home/ubuntu/miniconda3/envs/wham/lib/python3.9/site-packages/mmcv/cnn/bricks/transformer.py:27: UserWarning: Fail to import ``MultiScaleDeformableAttention`` from ``mmcv.ops.multi_scale_deform_attn``, You should install ``mmcv-full`` if you need this module.
  warnings.warn('Fail to import ``MultiScaleDeformableAttention`` from '
Traceback (most recent call last):
  File "/home/ubuntu/WHAM/demo.py", line 207, in <module>
    cfg.merge_from_file('configs/yamls/demo_w_fit.yaml')
  File "/home/ubuntu/miniconda3/envs/wham/lib/python3.9/site-packages/yacs/config.py", line 211, in merge_from_file
    with open(cfg_filename, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'configs/yamls/demo_w_fit.yaml'
```.
Before pulling the new version it was working.

**Comment by mrEuler** [comment]
Actually I just renamed 'configs/yamls/demo_w_fit.yaml' to 'configs/yamls/demo.yaml' in demo.py file and it worked,

**Comment by yohanshin** [comment]
Thanks @mrEuler for pointing this out. Yes, there was a mistake during the implementation and now fixed this issue and merged.
