### ISSUE TITLE
J_regressor_wham.npy  where down it?

### ISSUE THREAD

**Issue by zephirusgit** [yohanshin/WHAM#65]
python demo.py --video dance.mp4 --visualize
2024-03-04 19:44:25.282 | INFO     | __main__:<module>:27 - DPVO is not properly installed. Only estimate in local coordinates !
2024-03-04 19:44:25.316 | INFO     | __main__:<module>:209 - GPU name -> NVIDIA GeForce RTX 2060
2024-03-04 19:44:25.316 | INFO     | __main__:<module>:210 - GPU feat -> _CudaDeviceProperties(name='NVIDIA GeForce RTX 2060', major=7, minor=5, total_memory=12287MB, multi_processor_count=34)
Traceback (most recent call last):
  File "C:\ia\wham\WHAM\demo.py", line 214, in <module>
    smpl = build_body_model(cfg.DEVICE, smpl_batch_size)
  File "C:\ia\wham\WHAM\lib\models\__init__.py", line 12, in build_body_model
    body_model = SMPL(
  File "C:\ia\wham\WHAM\lib\models\smpl.py", line 25, in __init__
    J_regressor_wham = np.load(_C.BMODEL.JOINTS_REGRESSOR_WHAM)
  File "C:\Users\ultim\miniconda3\envs\wham\lib\site-packages\numpy\lib\npyio.py", line 427, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'dataset/body_models/J_regressor_wham.npy'

any idea?

**Comment by yohanshin** [comment]
All SMPL-related auxiliary data can be downloaded from the [Google Drive](https://drive.google.com/drive/folders/1LDMzLxv2ImCFwVZM_aWHlTSaX311gWP-?usp=sharing). You will get everything downloaded by running 
```bash 
bash ./fetch_demo_data.sh
```

**Comment by GaigeY** [comment]
> All SMPL-related auxiliary data can be downloaded from the [Google Drive](https://drive.google.com/drive/folders/1LDMzLxv2ImCFwVZM_aWHlTSaX311gWP-?usp=sharing). You will get everything downloaded by running
> 
> ```shell
> bash ./fetch_demo_data.sh
> ```

Hi Soyong Shin,

Thanks for your patience and detailed tutorial.

I‘ve noticed that the current version of `fetch_demo_data.sh` doesn't contain the download addresses of files like `J_regressor_wham.npy`, and the two dependecy files `smpl_mean_params.npz` and `smpl_faces.npy` haven't been metioned yet.

May I ask if the fetch script is missing some of the dependency files?

Best regrads,

Qijun Ying

**Comment by Eggwardhan** [comment]
> > All SMPL-related auxiliary data can be downloaded from the [Google Drive](https://drive.google.com/drive/folders/1LDMzLxv2ImCFwVZM_aWHlTSaX311gWP-?usp=sharing). You will get everything downloaded by running
> > bash ./fetch_demo_data.sh
> 
> Hi Soyong Shin,
> 
> Thanks for your patience and detailed tutorial.
> 
> I‘ve noticed that the current version of `fetch_demo_data.sh` doesn't contain the download addresses of files like `J_regressor_wham.npy`, and the two dependecy files `smpl_mean_params.npz` and `smpl_faces.npy` haven't been metioned yet.
> 
> May I ask if the fetch script is missing some of the dependency files?
> 
> Best regrads,
> 
> Qijun Ying
The script seems to complete, but you may meet error when run fetch_xx.sh, you can check and repair it.
