### ISSUE TITLE
Error related to ffmpeg

### ISSUE THREAD

**Issue by minjung98** [yohanshin/WHAM#97]
Thank you for nice work!
When I run demo.py file, `python demo.py --video examples/IMG_9732.mov --visualize`
The following error occurs. I have tried setting environment variables for ffmpeg and various other solutions, but to no avail.
How can I solve this problem?
`Traceback (most recent call last):
  File "/home/minjung/WHAM/demo.py", line 223, in <module>
    run(cfg, 
  File "/home/minjung/WHAM/demo.py", line 177, in run
    run_vis_on_demo(cfg, video, results, output_pth, network.smpl, vis_global=run_global)
  File "/home/minjung/WHAM/lib/vis/run_vis.py", line 89, in run_vis_on_demo
    writer.append_data(img)
  File "/home/minjung/anaconda3/envs/wham/lib/python3.9/site-packages/imageio/core/format.py", line 590, in append_data
    return self._append_data(im, total_meta)
  File "/home/minjung/anaconda3/envs/wham/lib/python3.9/site-packages/imageio/plugins/ffmpeg.py", line 587, in _append_data
    self._initialize()
  File "/home/minjung/anaconda3/envs/wham/lib/python3.9/site-packages/imageio/plugins/ffmpeg.py", line 648, in _initialize
    self._write_gen.send(None)
  File "/home/minjung/anaconda3/envs/wham/lib/python3.9/site-packages/imageio_ffmpeg/_io.py", line 508, in write_frames
    codec = get_first_available_h264_encoder()
  File "/home/minjung/anaconda3/envs/wham/lib/python3.9/site-packages/imageio_ffmpeg/_io.py", line 124, in get_first_available_h264_encoder
    compiled_encoders = get_compiled_h264_encoders()
  File "/home/minjung/anaconda3/envs/wham/lib/python3.9/site-packages/imageio_ffmpeg/_io.py", line 58, in get_compiled_h264_encoders
    cmd = [get_ffmpeg_exe(), "-hide_banner", "-encoders"]
  File "/home/minjung/anaconda3/envs/wham/lib/python3.9/site-packages/imageio_ffmpeg/_utils.py", line 28, in get_ffmpeg_exe
    exe = _get_ffmpeg_exe()
  File "/home/minjung/anaconda3/envs/wham/lib/python3.9/site-packages/imageio_ffmpeg/_utils.py", line 44, in _get_ffmpeg_exe
    exe = os.path.join(_get_bin_dir(), FNAME_PER_PLATFORM.get(plat, ""))
  File "/home/minjung/anaconda3/envs/wham/lib/python3.9/site-packages/imageio_ffmpeg/_utils.py", line 69, in _get_bin_dir
    ref = importlib.resources.files("imageio_ffmpeg.binaries") / "__init__.py"
  File "/home/minjung/anaconda3/envs/wham/lib/python3.9/importlib/resources.py", line 147, in files
    return _common.from_package(_get_package(package))
  File "/home/minjung/anaconda3/envs/wham/lib/python3.9/importlib/_common.py", line 14, in from_package
    return fallback_resources(package.__spec__)
  File "/home/minjung/anaconda3/envs/wham/lib/python3.9/importlib/_common.py", line 18, in fallback_resources
    package_directory = pathlib.Path(spec.origin).parent
  File "/home/minjung/anaconda3/envs/wham/lib/python3.9/pathlib.py", line 1082, in __new__
    self = cls._from_parts(args, init=False)
  File "/home/minjung/anaconda3/envs/wham/lib/python3.9/pathlib.py", line 707, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/home/minjung/anaconda3/envs/wham/lib/python3.9/pathlib.py", line 691, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
`

**Comment by yohanshin** [comment]
Hi @minjung98 , it seems like there is some error in the path setting. Is your writer set to the correct path (i.e., the base folder exists?)

**Comment by jiiiisoo** [comment]
I had same issue but by upgrading imageio-ffmpeg via `pip install --upgrade imageio-ffmpeg`, solved it.
